import { defaultVocabularyOptions, type VocabularyAdvancedOptions, type VocabularyExerciseType } from "@english-talks/shared";
import type { VocabularyTopic, VocabularyTopicKeyword } from "@prisma/client";

type TopicWithKeywords = VocabularyTopic & {
  keywords: VocabularyTopicKeyword[];
};

const wordCloudPositions = [
  { x: 48, y: 48, rotation: -6, scale: 1.45 },
  { x: 35, y: 35, rotation: -18, scale: 1.15 },
  { x: 63, y: 37, rotation: 12, scale: 1.05 },
  { x: 25, y: 58, rotation: 18, scale: 0.92 },
  { x: 71, y: 59, rotation: -14, scale: 0.88 },
  { x: 21, y: 27, rotation: 32, scale: 0.8 },
  { x: 79, y: 28, rotation: -28, scale: 0.86 },
  { x: 18, y: 72, rotation: -36, scale: 0.74 },
  { x: 84, y: 73, rotation: 27, scale: 0.79 },
];

function normalizeOptions(input?: Partial<VocabularyAdvancedOptions>): VocabularyAdvancedOptions {
  return {
    ...defaultVocabularyOptions,
    ...input,
    exerciseTypes: input?.exerciseTypes?.length ? input.exerciseTypes : defaultVocabularyOptions.exerciseTypes,
  };
}

function buildKeywordIntro(words: { term: string; definition: string }[]) {
  return words
    .map((word) => `${word.term} - ${word.definition}`)
    .join("\n");
}

function buildReadAloudPassage(topicTitles: string[], words: { term: string }[]) {
  const [first, second, third] = words;

  return `English Talks created this exercise to practice the following words:\n\n${first.term}, ${second.term}, and ${third.term}.\n\nPlease read the text out loud paying attention to the keywords. This text is generated by artificial intelligence.\n\nIn conversations about ${topicTitles.join(", ").toLowerCase()}, people often need a clear way to explain ideas. For example, ${first.term} can help us describe one key issue, ${second.term} can show why the issue matters, and ${third.term} can guide us toward a practical response. When learners speak with specific vocabulary, their answers become more precise, confident, and memorable.`;
}

function buildQuestionBlock(words: { term: string; definition: string }[]) {
  return [
    "Questions:",
    `1. What does the term ${words[0].term} mean and how is it used in real life?`,
    `2. Why is ${words[1].term} important in this topic, and what are some examples?`,
    `3. How can people improve ${words[2].term} in daily life, study, or work?`,
  ].join("\n");
}

function buildStoryPrompt(topicTitles: string[], words: { term: string }[]) {
  return `Tell a story that includes the key words ${words.map((word) => word.term).join(", ")}. Try to speak for at least one minute and connect your story to ${topicTitles.join(" and ")}.`;
}

export function createVocabularySessionBlueprint(topics: TopicWithKeywords[], rawOptions?: Partial<VocabularyAdvancedOptions>) {
  const options = normalizeOptions(rawOptions);
  const collectedKeywords = topics.flatMap((topic) => topic.keywords.map((keyword) => ({ ...keyword, topicTitle: topic.title })));

  const chosenWords = collectedKeywords.slice(0, options.wordCount).map((word, index) => {
    const position = wordCloudPositions[index] ?? wordCloudPositions[wordCloudPositions.length - 1];

    return {
      term: word.term,
      definition: word.definition,
      samplePrompt: word.samplePrompt,
      emphasisRank: index + 1,
      positionX: position.x,
      positionY: position.y,
      rotationDeg: position.rotation,
      fontScale: position.scale,
    };
  });

  const topicTitles = topics.map((topic) => topic.title);
  const keywordSummary = buildKeywordIntro(chosenWords);
  const readAloudPassage = buildReadAloudPassage(topicTitles, chosenWords);
  const questionBlock = buildQuestionBlock(chosenWords);
  const storyPrompt = buildStoryPrompt(topicTitles, chosenWords);

  const exerciseDefinitions: Record<
    VocabularyExerciseType,
    { title: string; instructions: string; referenceText?: string; questionBlock?: string; minDurationSeconds: number }
  > = {
    READ_ALOUD: {
      title: "Read the text out loud",
      instructions: "Please read the text out loud paying attention to the keywords.",
      referenceText: readAloudPassage,
      minDurationSeconds: Math.min(options.timerSeconds, 75),
    },
    KEYWORD_QA: {
      title: "Answer the questions using key words",
      instructions: "Use the highlighted key words naturally while answering each question.",
      questionBlock,
      minDurationSeconds: Math.max(options.timerSeconds, 60),
    },
    STORY: {
      title: "Tell a story that includes the key words",
      instructions: storyPrompt,
      minDurationSeconds: Math.max(options.timerSeconds, 60),
    },
  };

  const exercises = options.exerciseTypes.map((type, index) => ({
    exerciseType: type,
    orderIndex: index + 1,
    ...exerciseDefinitions[type],
  }));

  return {
    options,
    title: `${topicTitles.join(", ")} vocabulary practice`,
    topicSummary: topicTitles.join(", "),
    generatedPrompt: keywordSummary,
    words: chosenWords,
    exercises,
  };
}

