"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import {
  defaultVocabularyOptions,
  vocabularyKeywordBank,
  vocabularyTopics,
} from "../lib/site-content";
import type { VocabularyAdvancedOptions, VocabularyExerciseType } from "../lib/site-models";

type TopicSummary = {
  slug: string;
  title: string;
  emoji: string;
  description: string;
  category: string;
  suggestedKeywords?: string[];
};

type PracticeWord = {
  id?: string;
  term: string;
  definition: string;
  samplePrompt?: string;
  emphasisRank: number;
  positionX: number;
  positionY: number;
  rotationDeg: number;
  fontScale: number;
};

type PracticeExercise = {
  id: string;
  exerciseType: VocabularyExerciseType;
  title: string;
  instructions: string;
  referenceText?: string | null;
  questionBlock?: string | null;
  minDurationSeconds: number;
  orderIndex: number;
};

type VocabularySessionData = {
  id: string;
  title: string;
  level: string;
  status: string;
  topicSummary: string;
  targetMinutes: number;
  timerSeconds: number;
  feedbackMode: string;
  accentFocus: string;
  advancedOptions: VocabularyAdvancedOptions;
  generatedPrompt?: string | null;
  topics: TopicSummary[];
  words: PracticeWord[];
  exercises: PracticeExercise[];
  attempts: {
    id: string;
    exerciseId: string;
    transcriptText?: string | null;
    durationSeconds?: number | null;
    feedbackSummary?: string | null;
    status: string;
    createdAt: string;
  }[];
};

const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

const exerciseTypeLabels: Record<VocabularyExerciseType, string> = {
  READ_ALOUD: "Read aloud",
  KEYWORD_QA: "Questions",
  STORY: "Story",
};

const exerciseTypeOptions: VocabularyExerciseType[] = ["READ_ALOUD", "KEYWORD_QA", "STORY"];

function createFallbackSession(selectedTopicSlugs: string[], options: VocabularyAdvancedOptions): VocabularySessionData {
  const topics = vocabularyTopics.filter((topic) => selectedTopicSlugs.includes(topic.slug));
  const words = topics
    .flatMap((topic) => vocabularyKeywordBank[topic.slug] ?? [])
    .slice(0, options.wordCount)
    .map((keyword, index) => {
      const positions = [
        { x: 48, y: 48, rotation: -6, scale: 1.45 },
        { x: 36, y: 35, rotation: -18, scale: 1.1 },
        { x: 63, y: 39, rotation: 16, scale: 1.18 },
        { x: 24, y: 61, rotation: 24, scale: 0.92 },
        { x: 72, y: 60, rotation: -21, scale: 0.9 },
      ][index] ?? { x: 50, y: 50, rotation: 0, scale: 1 };

      return {
        id: `fallback-word-${index + 1}`,
        term: keyword.term,
        definition: keyword.definition,
        samplePrompt: keyword.samplePrompt,
        emphasisRank: index + 1,
        positionX: positions.x,
        positionY: positions.y,
        rotationDeg: positions.rotation,
        fontScale: positions.scale,
      };
    });

  const formattedWordList = words.map((word) => `${word.term} - ${word.definition}`).join("\n");

  const exercises: PracticeExercise[] = options.exerciseTypes.map((exerciseType, index) => {
    if (exerciseType === "READ_ALOUD") {
      return {
        id: `exercise-read-${index + 1}`,
        exerciseType,
        title: "Read the text out loud",
        instructions: "Please read the text out loud paying attention to the keywords.",
        referenceText: `English Talks created this exercise to practice the following words:\n\n${formattedWordList}\n\nPlease read the text out loud paying attention to the keywords. This text is generated by artificial intelligence.\n\n${words.map((word) => `Using ${word.term} correctly helps learners speak with more precision and confidence.`).join(" ")}`,
        minDurationSeconds: options.timerSeconds,
        orderIndex: index + 1,
      };
    }

    if (exerciseType === "KEYWORD_QA") {
      return {
        id: `exercise-qa-${index + 1}`,
        exerciseType,
        title: "Answer the questions using key words",
        instructions: "Use the highlighted key words naturally while answering each question.",
        questionBlock: [
          "Questions:",
          ...words.map((word, wordIndex) => `${wordIndex + 1}. How would you explain or use ${word.term} in a real conversation?`),
        ].join("\n"),
        minDurationSeconds: options.timerSeconds,
        orderIndex: index + 1,
      };
    }

    return {
      id: `exercise-story-${index + 1}`,
      exerciseType,
      title: "Tell a story that includes the key words",
      instructions: `Tell a story that includes the key words ${words.map((word) => word.term).join(", ")}. Try to speak at least 1 minute.`,
      minDurationSeconds: options.timerSeconds,
      orderIndex: index + 1,
    };
  });

  return {
    id: `fallback-session-${Date.now()}`,
    title: `${topics.map((topic) => topic.title).join(", ")} vocabulary practice`,
    level: options.level,
    status: "READY",
    topicSummary: topics.map((topic) => topic.title).join(", "),
    targetMinutes: options.targetMinutes,
    timerSeconds: options.timerSeconds,
    feedbackMode: options.feedbackMode,
    accentFocus: options.accentFocus,
    advancedOptions: options,
    generatedPrompt: formattedWordList,
    topics,
    words,
    exercises,
    attempts: [],
  };
}

function formatTimer(totalSeconds: number) {
  const minutes = Math.floor(totalSeconds / 60)
    .toString()
    .padStart(2, "0");
  const seconds = (totalSeconds % 60).toString().padStart(2, "0");
  return `${minutes}:${seconds}`;
}

export function VocabularyBoosterExperience() {
  const [stage, setStage] = useState<"landing" | "topics" | "cloud" | "exercise" | "complete">("landing");
  const [selectedTopics, setSelectedTopics] = useState<string[]>(["home"]);
  const [options, setOptions] = useState<VocabularyAdvancedOptions>(defaultVocabularyOptions);
  const [session, setSession] = useState<VocabularySessionData | null>(null);
  const [exerciseIndex, setExerciseIndex] = useState(0);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const [isRecording, setIsRecording] = useState(false);
  const [isPaused, setIsPaused] = useState(true);
  const [notes, setNotes] = useState("");
  const [attemptsSaved, setAttemptsSaved] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastAudioUrl, setLastAudioUrl] = useState<string | null>(null);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  const currentExercise = session?.exercises[exerciseIndex] ?? null;

  useEffect(() => {
    if (!isRecording || isPaused) {
      return;
    }

    const intervalId = window.setInterval(() => {
      setElapsedSeconds((current) => current + 1);
    }, 1000);

    return () => window.clearInterval(intervalId);
  }, [isRecording, isPaused]);

  useEffect(() => {
    return () => {
      mediaRecorderRef.current?.stop();
      mediaStreamRef.current?.getTracks().forEach((track) => track.stop());
      if (lastAudioUrl) {
        URL.revokeObjectURL(lastAudioUrl);
      }
    };
  }, [lastAudioUrl]);

  async function handleStartRecording() {
    setError(null);

    if (!navigator.mediaDevices?.getUserMedia) {
      setError("Microphone recording is not supported in this browser. You can still type notes and save the attempt.");
      setIsRecording(true);
      setIsPaused(false);
      return;
    }

    try {
      if (!mediaStreamRef.current) {
        mediaStreamRef.current = await navigator.mediaDevices.getUserMedia({ audio: true });
      }

      if (!mediaRecorderRef.current) {
        const recorder = new MediaRecorder(mediaStreamRef.current);
        audioChunksRef.current = [];

        recorder.ondataavailable = (event) => {
          if (event.data.size > 0) {
            audioChunksRef.current.push(event.data);
          }
        };

        recorder.onstop = () => {
          if (audioChunksRef.current.length === 0) {
            return;
          }

          const audioBlob = new Blob(audioChunksRef.current, { type: "audio/webm" });
          if (lastAudioUrl) {
            URL.revokeObjectURL(lastAudioUrl);
          }
          setLastAudioUrl(URL.createObjectURL(audioBlob));
        };

        mediaRecorderRef.current = recorder;
      }

      if (mediaRecorderRef.current.state === "inactive") {
        mediaRecorderRef.current.start();
      }

      setIsRecording(true);
      setIsPaused(false);
    } catch {
      setError("Microphone permission was denied. You can continue with typed notes and manual progress tracking.");
      setIsRecording(true);
      setIsPaused(false);
    }
  }

  function handlePauseRecording() {
    setIsPaused(true);
  }

  function handleStopRecording() {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== "inactive") {
      mediaRecorderRef.current.stop();
    }
    setIsRecording(false);
    setIsPaused(true);
  }

  function toggleTopic(slug: string) {
    setSelectedTopics((current) => {
      if (current.includes(slug)) {
        return current.filter((entry) => entry !== slug);
      }

      if (current.length >= 5) {
        return current;
      }

      return [...current, slug];
    });
  }

  function updateOption<K extends keyof VocabularyAdvancedOptions>(key: K, value: VocabularyAdvancedOptions[K]) {
    setOptions((current) => ({ ...current, [key]: value }));
  }

  function toggleExerciseType(type: VocabularyExerciseType) {
    setOptions((current) => {
      const alreadyIncluded = current.exerciseTypes.includes(type);
      const nextTypes = alreadyIncluded
        ? current.exerciseTypes.filter((entry) => entry !== type)
        : [...current.exerciseTypes, type];

      return {
        ...current,
        exerciseTypes: nextTypes.length > 0 ? nextTypes : current.exerciseTypes,
      };
    });
  }

  async function generateSession() {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch(`${apiBaseUrl}/api/v1/vocabulary/sessions`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topicSlugs: selectedTopics,
          options,
        }),
      });

      if (!response.ok) {
        throw new Error("Unable to create session");
      }

      const payload = (await response.json()) as { session: VocabularySessionData };
      setSession(payload.session);
      setExerciseIndex(0);
      setAttemptsSaved([]);
      setNotes("");
      setElapsedSeconds(0);
      setStage("cloud");
    } catch {
      const fallbackSession = createFallbackSession(selectedTopics, options);
      setSession(fallbackSession);
      setExerciseIndex(0);
      setAttemptsSaved([]);
      setNotes("");
      setElapsedSeconds(0);
      setStage("cloud");
      setError("Using local demo mode because the API session generator is unavailable right now.");
    } finally {
      setLoading(false);
    }
  }

  async function saveAttemptAndContinue() {
    if (!session || !currentExercise) {
      return;
    }

    setLoading(true);

    try {
      await fetch(`${apiBaseUrl}/api/v1/vocabulary/sessions/${session.id}/attempts`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          exerciseId: currentExercise.id,
          transcriptText: notes,
          durationSeconds: elapsedSeconds,
          feedbackSummary:
            options.feedbackMode === "exam"
              ? "Exam-style review requested."
              : options.feedbackMode === "detailed"
                ? "Detailed coaching review requested."
                : "Basic vocabulary review requested.",
          status: exerciseIndex === session.exercises.length - 1 ? "SUBMITTED" : "SAVED",
        }),
      });
    } catch {
      setError("Attempt could not be saved to the backend, but your local progress is still preserved on this page.");
    } finally {
      setAttemptsSaved((current) => [...current, currentExercise.id]);
      setNotes("");
      setElapsedSeconds(0);
      setIsRecording(false);
      setIsPaused(true);
      setLoading(false);

      if (exerciseIndex >= session.exercises.length - 1) {
        setStage("complete");
      } else {
        setExerciseIndex((current) => current + 1);
      }
    }
  }

  const selectedTopicCards = vocabularyTopics.filter((topic) => selectedTopics.includes(topic.slug));

  return (
    <div className="stack-lg">
      {stage === "landing" ? (
        <section className="vocab-hero">
          <div className="vocab-hero-copy stack-md">
            <h1 className="headline" style={{ fontSize: "clamp(2.2rem, 5vw, 3.5rem)" }}>
              AI-Powered Vocabulary Booster
            </h1>
            <p className="muted" style={{ margin: 0, fontSize: "1.12rem", maxWidth: 600 }}>
              Learn new words that our AI thinks fit your interests and English level. Build a
              full speaking workout with topic selection, timed tasks, advanced settings, and saved
              practice attempts.
            </p>
            <div style={{ display: "flex", gap: "0.85rem", flexWrap: "wrap" }}>
              <button className="button-primary" type="button" onClick={() => setStage("topics")}>
                Start practice
              </button>
              <Link className="button-secondary" href="/dashboard">
                Back to dashboard
              </Link>
            </div>
          </div>
          <div className="vocab-bot-card" aria-hidden="true">
            <div className="vocab-bot-face">
              <span />
              <span />
            </div>
            <div className="vocab-bot-body" />
          </div>
        </section>
      ) : null}

      {stage === "topics" ? (
        <section className="vocab-builder">
          <div className="vocab-builder-header">
            <div className="stack-sm">
              <span className="pill">Vocabulary Builder</span>
              <h2 className="headline" style={{ fontSize: "clamp(1.8rem, 4vw, 2.7rem)" }}>
                Choose practice topics
              </h2>
              <p className="muted" style={{ margin: 0 }}>
                Pick up to 5 themes, then fine-tune the session with level, timer, feedback mode,
                and exercise types.
              </p>
            </div>
            <button className="vocab-close" type="button" onClick={() => setStage("landing")}>
              ×
            </button>
          </div>

          <div className="vocab-builder-layout">
            <div className="vocab-topics-grid">
              {vocabularyTopics.map((topic) => {
                const isSelected = selectedTopics.includes(topic.slug);

                return (
                  <button
                    key={topic.slug}
                    type="button"
                    className={`vocab-topic-card ${isSelected ? "is-selected" : ""}`}
                    onClick={() => toggleTopic(topic.slug)}
                    aria-pressed={isSelected}
                  >
                    <span className={`vocab-topic-radio ${isSelected ? "is-selected" : ""}`} />
                    <div className="stack-sm" style={{ justifySelf: "start", textAlign: "left" }}>
                      <strong>{topic.title}</strong>
                      <span className="muted" style={{ fontSize: "0.92rem" }}>
                        {topic.description}
                      </span>
                    </div>
                    <span style={{ fontSize: "1.8rem" }}>{topic.emoji}</span>
                  </button>
                );
              })}
            </div>

            <aside className="vocab-settings-panel">
              <div className="stack-sm">
                <span className="pill">Advanced options</span>
                <strong style={{ fontSize: "1.2rem" }}>Session controls</strong>
                <p className="muted" style={{ margin: 0 }}>
                  Configure difficulty, feedback depth, pacing, timer behavior, and exercise
                  sequence.
                </p>
              </div>

              <div className="vocab-form-grid">
                <label className="vocab-field">
                  <span>Level</span>
                  <select value={options.level} onChange={(event) => updateOption("level", event.target.value as VocabularyAdvancedOptions["level"])}>
                    {["A2", "B1", "B2", "C1"].map((level) => (
                      <option key={level} value={level}>
                        {level}
                      </option>
                    ))}
                  </select>
                </label>

                <label className="vocab-field">
                  <span>Target minutes</span>
                  <input
                    type="number"
                    min={3}
                    max={20}
                    value={options.targetMinutes}
                    onChange={(event) => updateOption("targetMinutes", Number(event.target.value))}
                  />
                </label>

                <label className="vocab-field">
                  <span>Keyword count</span>
                  <input
                    type="number"
                    min={3}
                    max={6}
                    value={options.wordCount}
                    onChange={(event) => updateOption("wordCount", Number(event.target.value))}
                  />
                </label>

                <label className="vocab-field">
                  <span>Timer seconds</span>
                  <input
                    type="number"
                    min={30}
                    max={180}
                    value={options.timerSeconds}
                    onChange={(event) => updateOption("timerSeconds", Number(event.target.value))}
                  />
                </label>

                <label className="vocab-field">
                  <span>Feedback mode</span>
                  <select
                    value={options.feedbackMode}
                    onChange={(event) => updateOption("feedbackMode", event.target.value as VocabularyAdvancedOptions["feedbackMode"])}
                  >
                    <option value="basic">Basic</option>
                    <option value="detailed">Detailed</option>
                    <option value="exam">Exam style</option>
                  </select>
                </label>

                <label className="vocab-field">
                  <span>Accent focus</span>
                  <select
                    value={options.accentFocus}
                    onChange={(event) => updateOption("accentFocus", event.target.value as VocabularyAdvancedOptions["accentFocus"])}
                  >
                    <option value="general">General</option>
                    <option value="american">American</option>
                    <option value="british">British</option>
                  </select>
                </label>
              </div>

              <div className="stack-sm">
                <strong>Include features</strong>
                <div className="vocab-toggle-list">
                  {[
                    ["includeDefinitions", "Definitions"],
                    ["includeHints", "Prompt hints"],
                    ["includeTimer", "Visible timer"],
                  ].map(([key, label]) => (
                    <label key={key} className="vocab-check">
                      <input
                        type="checkbox"
                        checked={options[key as keyof VocabularyAdvancedOptions] as boolean}
                        onChange={(event) =>
                          updateOption(key as keyof VocabularyAdvancedOptions, event.target.checked as never)
                        }
                      />
                      <span>{label}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="stack-sm">
                <strong>Exercise types</strong>
                <div className="vocab-toggle-list">
                  {exerciseTypeOptions.map((type) => (
                    <label key={type} className="vocab-check">
                      <input
                        type="checkbox"
                        checked={options.exerciseTypes.includes(type)}
                        onChange={() => toggleExerciseType(type)}
                      />
                      <span>{exerciseTypeLabels[type]}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="stack-sm">
                <strong>Selected topics</strong>
                <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
                  {selectedTopicCards.map((topic) => (
                    <span key={topic.slug} className="pill">
                      {topic.emoji} {topic.title}
                    </span>
                  ))}
                </div>
              </div>

              <button
                className="button-primary"
                type="button"
                disabled={selectedTopics.length === 0 || loading}
                onClick={generateSession}
              >
                {loading ? "Building session..." : "Next"}
              </button>
            </aside>
          </div>
        </section>
      ) : null}

      {stage === "cloud" && session ? (
        <section className="vocab-stage-card">
          <div className="vocab-builder-header">
            <div className="stack-sm">
              <strong style={{ fontSize: "1.3rem" }}>AI keyword cloud</strong>
              <p className="muted" style={{ margin: 0 }}>
                Review your generated vocabulary set before starting the speaking tasks.
              </p>
            </div>
            <button className="vocab-close" type="button" onClick={() => setStage("topics")}>
              ×
            </button>
          </div>

          <div className="vocab-word-cloud">
            {session.words.map((word) => (
              <span
                key={word.term}
                className="vocab-cloud-word"
                style={{
                  left: `${word.positionX}%`,
                  top: `${word.positionY}%`,
                  transform: `translate(-50%, -50%) rotate(${word.rotationDeg}deg) scale(${word.fontScale})`,
                  opacity: word.emphasisRank <= 3 ? 1 : 0.55,
                }}
              >
                {word.term}
              </span>
            ))}
          </div>

          <div className="vocab-stage-actions">
            <button className="button-secondary" type="button" onClick={generateSession}>
              Try again
            </button>
            <button className="button-primary" type="button" onClick={() => setStage("exercise")}>
              Next
            </button>
          </div>
        </section>
      ) : null}

      {stage === "exercise" && session && currentExercise ? (
        <section className="vocab-exercise-shell">
          <div className="vocab-exercise-topbar">
            <span className="pill">{session.topicSummary}</span>
            <div className="vocab-progress-badge">
              Total: {exerciseIndex + 1} / {session.exercises.length}{" "}
              <strong>{formatTimer(elapsedSeconds)}</strong>
            </div>
          </div>

          <div className="vocab-exercise-content">
            <div className="stack-md">
              <span className="pill">{exerciseTypeLabels[currentExercise.exerciseType]}</span>
              <h2 className="headline" style={{ fontSize: "clamp(1.9rem, 4vw, 3rem)" }}>
                {currentExercise.title}
              </h2>
              <div className="stack-sm">
                {options.includeDefinitions ? (
                  <div className="stack-sm">
                    {session.words.map((word) => (
                      <p key={word.term} style={{ margin: 0, fontSize: "1.05rem" }}>
                        <strong>{word.term}</strong> - {word.definition}
                      </p>
                    ))}
                  </div>
                ) : null}

                <p style={{ margin: 0, fontWeight: 600 }}>{currentExercise.instructions}</p>

                {currentExercise.referenceText ? (
                  <pre className="vocab-preformatted">{currentExercise.referenceText}</pre>
                ) : null}

                {currentExercise.questionBlock ? (
                  <pre className="vocab-preformatted">{currentExercise.questionBlock}</pre>
                ) : null}
              </div>
            </div>

            <aside className="vocab-side-panel">
              <div className="stack-sm">
                <strong>Advanced session data</strong>
                <div className="vocab-side-stat">
                  <span>Level</span>
                  <strong>{session.level}</strong>
                </div>
                <div className="vocab-side-stat">
                  <span>Feedback</span>
                  <strong>{session.feedbackMode}</strong>
                </div>
                <div className="vocab-side-stat">
                  <span>Accent</span>
                  <strong>{session.accentFocus}</strong>
                </div>
                <div className="vocab-side-stat">
                  <span>Minimum timer</span>
                  <strong>{formatTimer(currentExercise.minDurationSeconds)}</strong>
                </div>
              </div>

              {options.includeHints ? (
                <div className="panel route-card stack-sm">
                  <strong>Hint</strong>
                  <p className="muted" style={{ margin: 0 }}>
                    Reuse each keyword naturally, give one example, and end with a clear final
                    sentence.
                  </p>
                </div>
              ) : null}

              {lastAudioUrl ? (
                <div className="panel route-card stack-sm">
                  <strong>Last recording preview</strong>
                  <audio controls src={lastAudioUrl} />
                </div>
              ) : null}
            </aside>
          </div>

          <div className="vocab-reflection-box">
            <label className="vocab-field">
              <span>Transcript notes or self-reflection</span>
              <textarea
                rows={5}
                value={notes}
                onChange={(event) => setNotes(event.target.value)}
                placeholder="Write your transcript, key mistakes, or strong vocabulary you used..."
              />
            </label>
          </div>

          <div className="vocab-recorder-bar">
            <div style={{ display: "flex", gap: "0.8rem", flexWrap: "wrap" }}>
              {!isRecording || isPaused ? (
                <button className="button-primary" type="button" onClick={handleStartRecording}>
                  Record
                </button>
              ) : (
                <button className="button-secondary" type="button" onClick={handlePauseRecording}>
                  Pause
                </button>
              )}
              <button className="button-secondary" type="button" onClick={handleStopRecording}>
                Stop
              </button>
            </div>

            <span className="vocab-status-text">{isPaused ? "On pause" : "Recording..."}</span>

            <button className="button-primary" type="button" onClick={saveAttemptAndContinue} disabled={loading}>
              {exerciseIndex === session.exercises.length - 1 ? "Finish" : "Next"}
            </button>
          </div>

          {attemptsSaved.length > 0 ? (
            <p className="muted" style={{ margin: 0 }}>
              Saved attempts: {attemptsSaved.length} / {session.exercises.length}
            </p>
          ) : null}
        </section>
      ) : null}

      {stage === "complete" && session ? (
        <section className="vocab-complete-card">
          <div className="stack-md">
            <span className="pill">Session complete</span>
            <h2 className="headline" style={{ fontSize: "clamp(2rem, 4vw, 3rem)" }}>
              Your English Talks vocabulary workout is saved
            </h2>
            <p className="muted" style={{ margin: 0, maxWidth: 720 }}>
              You finished {session.exercises.length} exercises across {session.topics.length} topic
              areas. The backend can now keep session settings, keyword sets, and saved attempts for
              later reporting and feedback.
            </p>
            <div style={{ display: "flex", gap: "0.8rem", flexWrap: "wrap" }}>
              <button className="button-primary" type="button" onClick={() => setStage("topics")}>
                Create another session
              </button>
              <button className="button-secondary" type="button" onClick={() => setStage("cloud")}>
                Review keyword cloud
              </button>
            </div>
          </div>
        </section>
      ) : null}

      {error ? (
        <div className="panel route-card">
          <p style={{ margin: 0, color: "var(--orange)" }}>{error}</p>
        </div>
      ) : null}
    </div>
  );
}
